name: Release CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  workflow_call:

jobs:
  release:
    secrets: inherit
    uses: ./.github/workflows/check-new-releases.yaml
    strategy:
      fail-fast: false
      matrix:
        product:
          - name: spark
            lp-project: test-spark-build
            lp-repo: ~paolosottovia/test-spark-build/+git/test-spark-build
            lp-branch-prefix: spark-

          - name: opensearch
            lp-project: opensearch-lp-build
            lp-repo: ~medib/opensearch-lp-build/+git/opensearch-lp-build
            lp-branch-prefix: lp-
    with:
      name: ${{ matrix.product.name }}
      lp-project: ${{ matrix.product.lp-project }}
      lp-repo: ${{ matrix.product.lp-repo }}
      lp-branch-prefix: ${{ matrix.product.lp-branch-prefix }}
